apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: glueops-pod-in-bad-state
spec:
  groups:
  - name: glueops-pod-in-bad-state
    rules:
    - alert: glueops-pod-in-bad-state
      expr: |
        (kube_pod_status_phase{namespace=~"^(kube-system|glueops-core-.*|glueops-core)$", phase=~"^(Failed|Unknown|ContainerCreating|CrashLoopBackOff|ImagePullBackOff|ErrImageNeverPull)$"} == 1)
        or
        (kube_pod_status_ready{namespace=~"^(kube-system|glueops-core-.*|glueops-core)$", pod!~"^(captain-redis-ha-configmap-test|captain-redis-ha-service-test)$", condition="false"} == 1)
        or
        (kube_pod_status_restarts_total{namespace=~"^(kube-system|glueops-core-.*|glueops-core)$"} > 3)
      for: 1m
      annotations:
        description: A GlueOps pod is in a bad state.
      labels:
  {{ if ne (toString .Values.prometheus-alertmanagerconfig-opsgenie.labels.team) "nil" }}
        team: {{ .Values.prometheus-alertmanagerconfig-opsgenie.labels.team }}
  {{ end }}
  {{ if ne (toString .Values.prometheus-alertmanagerconfig-opsgenie.labels.component) "nil" }}
        component: {{ .Values.prometheus-alertmanagerconfig-opsgenie.labels.component }}
  {{ end }}
        alertname: {{ .Release.Name }}
        namespace: {{ .Release.Namespace }}
